name: Flutter CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Projeyi klonlama
      - uses: actions/checkout@v4

      # Flutter SDK'yı kurma

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.23.3" # Flutter'ın belirli bir stable sürümünü burada belirtiyoruz
      # Flutter Doctor
      - name: Run Flutter Doctor
        run: flutter doctor

      # Bağımlılıkları yükleme
      - name: Install dependencies
        run: flutter pub get

      # Format kontrolü (opsiyonel)
      - name: Verify formatting
        run: flutter format --set-exit-if-changed .

      # Kod analizi
      - name: Analyze project source
        run: flutter analyze

      # Testleri çalıştırma
      - name: Run tests
        run: flutter test
